apiVersion: v1
kind: Service
metadata:
  namespace: shape-up
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008
