apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shape-up
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hamza371/shape-up-backend:latest
          ports:
            - containerPort: 5000
