apiVersion: v1
kind: Service
metadata:
  namespace: shape-up
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
